# Generated by Django 4.1.3 on 2022-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
